### ISSUE TITLE
JSONDecodeError doing "cve.search('microsoft/office')"

### ISSUE THREAD

**Issue by ghost** [cve-search/PyCVESearch#19]
python 3.9 - running example gives exception

```>>> cve.search('microsoft/office')
Traceback (most recent call last):
  File "/Users/drace/opt/miniconda3/envs/mloperator/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/drace/opt/miniconda3/envs/mloperator/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/drace/opt/miniconda3/envs/mloperator/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/drace/opt/miniconda3/envs/mloperator/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/drace/opt/miniconda3/envs/mloperator/lib/python3.9/site-packages/pycvesearch/core.py", line 41, in search
    return data.json()
  File "/Users/drace/opt/miniconda3/envs/mloperator/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> ```

**Comment by Rafiot** [comment]
yes, the API has been removed from the public instance due to massive abuse of the interface. You'll need to install your own instance of CVESearch in order to use it.
