### ISSUE TITLE
Unicode error during setup.py install

### ISSUE THREAD

**Issue by NickMich** [cve-search/PyCVESearch#2]
Hello,

I'm getting the following error when executing:

`python3 setup.py install`

error:
`
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    long_description=open('README.md', 'r').read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1315: ordinal not in range(128)
`

It looks like the offending character is in this author's name found in README.md: 

`Copyright 2016 Raphaël Vinot`

Locally removing that line resolves the installation issue for me

**Comment by Rafiot** [comment]
This is weird, I don't have this problem (in either python2 or 3): 
```
$ (git::master) pew new -p python3 pycvesearch
Running virtualenv with interpreter /usr/bin/python3                                                               
Using base prefix '/usr'                                                                                                
New python executable in /home/raphael/.local/share/virtualenvs/pycvesearch/bin/python3
Also creating executable in /home/raphael/.local/share/virtualenvs/pycvesearch/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.                                                            
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

$ (git::master) python3 setup.py install                                                                                                                                
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_requires'
  warnings.warn(msg)          
running install                                          
running bdist_egg                                                                                                  
running egg_info                                                                      
writing pycvesearch.egg-info/PKG-INFO               
writing dependency_links to pycvesearch.egg-info/dependency_links.txt  
writing requirements to pycvesearch.egg-info/requires.txt                                                     
writing top-level names to pycvesearch.egg-info/top_level.txt                                                      
reading manifest file 'pycvesearch.egg-info/SOURCES.txt'
writing manifest file 'pycvesearch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg                                                        
running install_lib         
running build_py                            
creating build/bdist.linux-x86_64/egg                                                                                                                               
creating build/bdist.linux-x86_64/egg/pycvesearch
copying build/lib/pycvesearch/__init__.py -> build/bdist.linux-x86_64/egg/pycvesearch
copying build/lib/pycvesearch/core.py -> build/bdist.linux-x86_64/egg/pycvesearch
byte-compiling build/bdist.linux-x86_64/egg/pycvesearch/__init__.py to __init__.cpython-36.pyc             
byte-compiling build/bdist.linux-x86_64/egg/pycvesearch/core.py to core.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO                                      
copying pycvesearch.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycvesearch.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO                          
copying pycvesearch.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycvesearch.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycvesearch.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO                        
zip_safe flag not set; analyzing archive contents...
creating 'dist/pycvesearch-0.5-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)                                                                                                        
Processing pycvesearch-0.5-py3.6.egg
Copying pycvesearch-0.5-py3.6.egg to /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages
Adding pycvesearch 0.5 to easy-install.pth file           
                                                                                                                     
Installed /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/pycvesearch-0.5-py3.6.egg
Processing dependencies for pycvesearch==0.5        
Searching for requests                                                                                          
Reading https://pypi.python.org/simple/requests/
Downloading https://pypi.python.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz#md5=081412b2ef79bdc48229891af13f4d82
Best match: requests 2.18.4
Processing requests-2.18.4.tar.gz                                                                               
Writing /tmp/easy_install-1hvjm6y3/requests-2.18.4/setup.cfg
Running requests-2.18.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1hvjm6y3/requests-2.18.4/egg-dist-tmp-qr8on58g
warning: no files found matching 'NOTICE'
creating /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg
Extracting requests-2.18.4-py3.6.egg to /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages
Adding requests 2.18.4 to easy-install.pth file
                        
Installed /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg
Searching for certifi>=2017.4.17
Reading https://pypi.python.org/simple/certifi/
Downloading https://pypi.python.org/packages/23/3f/8be01c50ed24a4bd6b8da799839066ce0288f66f5e11f0367323467f0cbc/certifi-2017.11.5.tar.gz#md5=c15ac46ed1fe4b607ff3405928f9a992
Best match: certifi 2017.11.5
Processing certifi-2017.11.5.tar.gz
Writing /tmp/easy_install-vgf53ep8/certifi-2017.11.5/setup.cfg
Running certifi-2017.11.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vgf53ep8/certifi-2017.11.5/egg-dist-tmp-1hcfcpc4
/home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/setuptools/dist.py:347: UserWarning: Normalizing '2017.11.05' to '2017.11.5'
  normalized_version,
creating /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/certifi-2017.11.5-py3.6.egg
Extracting certifi-2017.11.5-py3.6.egg to /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages
Adding certifi 2017.11.5 to easy-install.pth file

Installed /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/certifi-2017.11.5-py3.6.egg
Searching for urllib3<1.23,>=1.21.1
Reading https://pypi.python.org/simple/urllib3/
Downloading https://pypi.python.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz#md5=0da7bed3fe94bf7dc59ae37885cc72f7
Best match: urllib3 1.22
Processing urllib3-1.22.tar.gz
Writing /tmp/easy_install-gqx0epxu/urllib3-1.22/setup.cfg
Running urllib3-1.22/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gqx0epxu/urllib3-1.22/egg-dist-tmp-g27xpj46
warning: no previously-included files matching '*' found under directory 'docs/_build'
zip_safe flag not set; analyzing archive contents...
urllib3.packages.__pycache__.six.cpython-36: module references __path__
creating /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg
Extracting urllib3-1.22-py3.6.egg to /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages
Adding urllib3 1.22 to easy-install.pth file

Installed /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg
Searching for idna<2.7,>=2.5
Reading https://pypi.python.org/simple/idna/
Downloading https://pypi.python.org/packages/f4/bd/0467d62790828c23c47fc1dfa1b1f052b24efdf5290f071c7a91d0d82fd3/idna-2.6.tar.gz#md5=c706e2790b016bd0ed4edd2d4ba4d147
Best match: idna 2.6
Processing idna-2.6.tar.gz
Writing /tmp/easy_install-pc2p2jwo/idna-2.6/setup.cfg
Running idna-2.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pc2p2jwo/idna-2.6/egg-dist-tmp-rvhhdl5f
warning: no previously-included files matching '*.pyc' found under directory 'tools'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
zip_safe flag not set; analyzing archive contents...
Moving idna-2.6-py3.6.egg to /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages
Adding idna 2.6 to easy-install.pth file

Installed /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/idna-2.6-py3.6.egg
Searching for chardet<3.1.0,>=3.0.2
Reading https://pypi.python.org/simple/chardet/
Downloading https://pypi.python.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz#md5=7dd1ba7f9c77e32351b0a0cfacf4055c
Best match: chardet 3.0.4
Processing chardet-3.0.4.tar.gz
Writing /tmp/easy_install-wkp765b2/chardet-3.0.4/setup.cfg
Running chardet-3.0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wkp765b2/chardet-3.0.4/egg-dist-tmp-05qzphoe
warning: no files found matching 'requirements.txt'
zip_safe flag not set; analyzing archive contents...
Moving chardet-3.0.4-py3.6.egg to /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/raphael/.local/share/virtualenvs/pycvesearch/bin

Installed /home/raphael/.local/share/virtualenvs/pycvesearch/lib/python3.6/site-packages/chardet-3.0.4-py3.6.egg
Finished processing dependencies for pycvesearch==0.5
```
